### ISSUE TITLE
Hi sorry but... I just don't figure out how to instal it ? After some time I found the Releases, but don't know how to install...

### ISSUE THREAD

**Issue by YukiMemories** [mauroalderete/virtualmic-pulseaudio#8]

**Comment by YukiMemories** [comment]
anyone ?

**Comment by YukiMemories** [comment]
well, nevermind, i found a way to stream obs sound to discord

**Comment by mauroalderete** [comment]
Hi, @YukiMemories 

I'm sorry, I've been swamped with work lately and I've not noted the GitHub notifications until now.

In the [home of the project](https://github.com/mauroalderete/virtualmic-pulseaudio) there is an install section... basically, you need to execute a script named `install.sh` in your Linux system using a terminal. This script requires root permissions since it will look to install some dependencies if them hasn't been installed yet.

Beyond that... I'm glad that you found another way to stream to Discord. If you are still interested in testing virtualmic yet, write me again

I’ll keep an eye on it!
